spring.application.name=gestion-administrativa-segundo-parcial-sw2
spring.config.import=optional:file:.env[.properties]

server.port=${SERVER_PORT:3001}
spring.profiles.active=${SPRING_PROFILES_ACTIVE:development}

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# GraphQL
spring.graphql.graphiql.enabled=${SPRING_GRAPHQL_GRAPHIQL_ENABLED:true}
spring.graphql.path=/graphql

# Blockchain MS-6
blockchain.service.url=${BLOCKCHAIN_SERVICE_URL}

# URL interna del microservicio clinica (NestJS) para enriquecimiento cross-service
clinica.graphql.url=${CLINICA_GRAPHQL_URL}

# AWS S3
aws.region=${AWS_REGION:us-east-2}
aws.access-key-id=${AWS_ACCESS_KEY_ID:}
aws.secret-access-key=${AWS_SECRET_ACCESS_KEY:}
aws.s3.bucket-name=${AWS_S3_BUCKET_NAME:erp-fisioterapia-docs}
